version: '3.8'

services:

  db:
    image: postgres:18
    container_name: Desarrollo
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql

  backend:
    build: ./server-fastapi # <-- Le dice a Docker que busque el Dockerfile aquí
    container_name: server-fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./server-fastapi:/app  # <-- Sincroniza tu código para que los cambios se vean en vivo
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432
    depends_on:
      - db

volumes:
  postgres_data:
